<?xml version="1.0" encoding="utf-8"?><Database Name="TeamPenguin" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=CPSLABSERVER\TEAMPENGUIN;Initial Catalog=TeamPenguin;Persist Security Info=True;User ID=sa" SettingsObjectName="Bounced_Check_Manager.Properties.Settings" SettingsPropertyName="TeamPenguinConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="AccID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AccAddress" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AccRoutNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>