#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bounced_Check_Manager
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TeamPenguin")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAccount(Account instance);
    partial void UpdateAccount(Account instance);
    partial void DeleteAccount(Account instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Bounced_Check_Manager.Properties.Settings.Default.TeamPenguinConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Check> Checks
		{
			get
			{
				return this.GetTable<Check>();
			}
		}
		
		public System.Data.Linq.Table<Store> Stores
		{
			get
			{
				return this.GetTable<Store>();
			}
		}
		
		public System.Data.Linq.Table<Account> Accounts
		{
			get
			{
				return this.GetTable<Account>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Check]")]
	public partial class Check
	{
		
		private int _Check_Number;
		
		private string _Bank_Name;
		
		private string _Bank_Address;
		
		private System.DateTime _Date_Written;
		
		private int _Total_Amount;
		
		private System.Nullable<int> _Cashier_ID;
		
		private int _Amount_Due;
		
		public Check()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Check Number]", Storage="_Check_Number", DbType="Int NOT NULL")]
		public int Check_Number
		{
			get
			{
				return this._Check_Number;
			}
			set
			{
				if ((this._Check_Number != value))
				{
					this._Check_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Bank Name]", Storage="_Bank_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Bank_Name
		{
			get
			{
				return this._Bank_Name;
			}
			set
			{
				if ((this._Bank_Name != value))
				{
					this._Bank_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Bank Address]", Storage="_Bank_Address", DbType="NVarChar(75)")]
		public string Bank_Address
		{
			get
			{
				return this._Bank_Address;
			}
			set
			{
				if ((this._Bank_Address != value))
				{
					this._Bank_Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Date Written]", Storage="_Date_Written", DbType="Date NOT NULL")]
		public System.DateTime Date_Written
		{
			get
			{
				return this._Date_Written;
			}
			set
			{
				if ((this._Date_Written != value))
				{
					this._Date_Written = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Total Amount]", Storage="_Total_Amount", DbType="Int NOT NULL")]
		public int Total_Amount
		{
			get
			{
				return this._Total_Amount;
			}
			set
			{
				if ((this._Total_Amount != value))
				{
					this._Total_Amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Cashier ID]", Storage="_Cashier_ID", DbType="Int")]
		public System.Nullable<int> Cashier_ID
		{
			get
			{
				return this._Cashier_ID;
			}
			set
			{
				if ((this._Cashier_ID != value))
				{
					this._Cashier_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Amount Due]", Storage="_Amount_Due", DbType="Int NOT NULL")]
		public int Amount_Due
		{
			get
			{
				return this._Amount_Due;
			}
			set
			{
				if ((this._Amount_Due != value))
				{
					this._Amount_Due = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Store")]
	public partial class Store
	{
		
		private int _StoreID;
		
		private string _StoreName;
		
		private int _StoreNum;
		
		private System.Nullable<decimal> _StoreServCharge;
		
		public Store()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreID", DbType="Int NOT NULL")]
		public int StoreID
		{
			get
			{
				return this._StoreID;
			}
			set
			{
				if ((this._StoreID != value))
				{
					this._StoreID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreName", DbType="VarChar(100)")]
		public string StoreName
		{
			get
			{
				return this._StoreName;
			}
			set
			{
				if ((this._StoreName != value))
				{
					this._StoreName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreNum", DbType="Int NOT NULL")]
		public int StoreNum
		{
			get
			{
				return this._StoreNum;
			}
			set
			{
				if ((this._StoreNum != value))
				{
					this._StoreNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreServCharge", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> StoreServCharge
		{
			get
			{
				return this._StoreServCharge;
			}
			set
			{
				if ((this._StoreServCharge != value))
				{
					this._StoreServCharge = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Account")]
	public partial class Account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AccID;
		
		private int _AccNo;
		
		private string _AccName;
		
		private string _AccAddress;
		
		private int _AccRoutNo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAccIDChanging(int value);
    partial void OnAccIDChanged();
    partial void OnAccNoChanging(int value);
    partial void OnAccNoChanged();
    partial void OnAccNameChanging(string value);
    partial void OnAccNameChanged();
    partial void OnAccAddressChanging(string value);
    partial void OnAccAddressChanged();
    partial void OnAccRoutNoChanging(int value);
    partial void OnAccRoutNoChanged();
    #endregion
		
		public Account()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AccID
		{
			get
			{
				return this._AccID;
			}
			set
			{
				if ((this._AccID != value))
				{
					this.OnAccIDChanging(value);
					this.SendPropertyChanging();
					this._AccID = value;
					this.SendPropertyChanged("AccID");
					this.OnAccIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccNo", DbType="Int NOT NULL")]
		public int AccNo
		{
			get
			{
				return this._AccNo;
			}
			set
			{
				if ((this._AccNo != value))
				{
					this.OnAccNoChanging(value);
					this.SendPropertyChanging();
					this._AccNo = value;
					this.SendPropertyChanged("AccNo");
					this.OnAccNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string AccName
		{
			get
			{
				return this._AccName;
			}
			set
			{
				if ((this._AccName != value))
				{
					this.OnAccNameChanging(value);
					this.SendPropertyChanging();
					this._AccName = value;
					this.SendPropertyChanged("AccName");
					this.OnAccNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccAddress", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string AccAddress
		{
			get
			{
				return this._AccAddress;
			}
			set
			{
				if ((this._AccAddress != value))
				{
					this.OnAccAddressChanging(value);
					this.SendPropertyChanging();
					this._AccAddress = value;
					this.SendPropertyChanged("AccAddress");
					this.OnAccAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccRoutNo", DbType="Int NOT NULL")]
		public int AccRoutNo
		{
			get
			{
				return this._AccRoutNo;
			}
			set
			{
				if ((this._AccRoutNo != value))
				{
					this.OnAccRoutNoChanging(value);
					this.SendPropertyChanging();
					this._AccRoutNo = value;
					this.SendPropertyChanged("AccRoutNo");
					this.OnAccRoutNoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
